#`baseurl = "https://EXAMPLE.COM"` задает базовый URL для сайта, который используется для построения абсолютных URL для страниц и активов на сайте. Это важно для обеспечения правильной ссылки на ссылки и ресурсы по всему сайту.
baseurl = "https://EXAMPLE.COM"
#`DefaultContentLanguage = "ru"` устанавливает язык по умолчанию для содержимого сайта - русский. Это важно для поисковых систем и целей доступности, так как помогает им понять язык содержимого и правильно отобразить его для пользователей.
DefaultContentLanguage = "ru"
#`title = "EXAMPLE"` устанавливает заголовок веб-сайта на "EXAMPLE". Этот заголовок обычно отображается на вкладке браузера, а также используется поисковыми системами для идентификации сайта.
title = "EXAMPLE"
#`theme = "beautifulhugo"` - это установка темы сайта "beautifulhugo". Это определяет общий внешний вид и настроение сайта, включая макет, типографику и цветовую схему. Тема - это предварительно разработанный шаблон, который можно настроить в соответствии с конкретными потребностями сайта.
theme = "beautifulhugo"
#`pygmentsStyle = "trac"` - это закомментированная строка кода, что означает, что в настоящее время она не активна в конфигурационном файле. Однако, если бы она была активна, она бы устанавливала стиль подсветки синтаксиса для блоков кода на сайте на "trac". Pygments - это библиотека подсветки синтаксиса, которая обычно используется в генераторах статических сайтов, таких как Hugo, для добавления цвета и форматирования к фрагментам кода. Параметр `pygmentsStyle` позволяет вам выбрать один из множества предопределенных стилей для подсветки синтаксиса.
# pygmentsStyle = "trac"
#`pygmentsUseClasses = true` - это еще одна закомментированная строка кода, что означает, что в настоящее время она не активна в конфигурационном файле. Однако если бы она была активна, то указывала бы Hugo на использование CSS-классов для подсветки синтаксиса вместо встроенных стилей. Это может быть полезно для отделения стилей блоков кода от содержимого сайта, что облегчает настройку внешнего вида и настроек сайта.
# pygmentsUseClasses = true
#`pygmentsCodeFences = true` - это еще одна закомментированная строка кода, что означает, что в настоящее время она не активна в конфигурационном файле. Однако если бы она была активна, то указывала бы Hugo на использование кодовых ограждений для подсветки синтаксиса вместо блоков кода по умолчанию. Кодовые ограждения - это способ заключить фрагменты кода в тройные обратные знаки (
# pygmentsCodeFences = true
#`pygmentsCodefencesGuessSyntax = true` - это еще одна закомментированная строка кода, что означает, что в настоящее время она не активна в конфигурационном файле. Однако, если бы она была активна, она бы подсказывала Хьюго угадывать синтаксис блоков кода, заключенных в кодовые ограждения, на основе языка, указанного в ограждении. Это может быть полезно в случаях, когда язык не указан явно, так как позволяет Hugo применять подсветку синтаксиса к блоку кода.
# pygmentsCodefencesGuessSyntax = true
#`pygmentsUseClassic = true` - это закомментированная строка кода, что означает, что она не активна в конфигурационном файле. Однако, если бы она была активна, она бы указывала Hugo использовать классический стиль Pygments для подсветки синтаксиса вместо стиля по умолчанию. Классический стиль - это более традиционный вид подсветки синтаксиса, с белым фоном и цветным текстом.
# pygmentsUseClassic = true
#`pygmentOptions = "linenos=inline"` - это закомментированная строка кода, что означает, что в настоящее время она не активна в конфигурационном файле. Однако, если бы она была активна, она бы устанавливала опции Pygments для подсветки синтаксиса. В данном случае, она устанавливает опцию `linenos` в `inline`, которая отображает номера строк для блоков кода в строке кода. Это может быть полезно для ссылок на конкретные строки кода в обсуждениях или объяснениях.
# pygmentOptions = "linenos=inline"
#`disqusShortname = "XXX"` - это закомментированная строка кода, что означает, что в настоящее время она не активна в конфигурационном файле. Однако, если бы она была активна, она бы устанавливала короткое имя системы комментирования Disqus на сайте на "XXX". Disqus - это сторонняя система комментирования, которая может быть интегрирована в сайт Hugo, чтобы посетители могли оставлять комментарии к постам и страницам. Параметр `disqusShortname` используется для идентификации учетной записи Disqus, связанной с сайтом.
# disqusShortname = "XXX"
#`googleAnalytics = "XXX"` - это закомментированная строка кода, что означает, что в настоящее время она не активна в конфигурационном файле. Однако, если бы она была активна, она бы устанавливала идентификатор отслеживания Google Analytics для сайта на "XXX". Google Analytics - это служба веб-аналитики, которая позволяет владельцам сайтов отслеживать и анализировать посещаемость сайта и поведение пользователей. Добавив идентификатор отслеживания Google Analytics в файл конфигурации, Hugo может автоматически включить необходимый код отслеживания на каждой странице сайта.
#googleAnalytics = "XXX"

[Params]
  #`homeTitle = "EXAMPLE TITLE"` - это закомментированная строка кода в конфигурационном файле для сайта Hugo. В настоящее время она не активна и не влияет на работу сайта. Если бы она была активна, она бы установила заголовок домашней страницы на "EXAMPLE TITLE".
  # homeTitle = "EXAMPLE TITLE"
  #`subtitle = "EXAMPLE SUBTITLE"` - это установка подзаголовка сайта на "EXAMPLE SUBTITLE". Подзаголовок обычно отображается под основным заголовком и предоставляет дополнительную информацию о сайте или его содержимом.
  subtitle = "EXAMPLE SUBTITLE"
  #`mainSections = ["post", "posts"]` - это установка основных разделов сайта на "post" и "posts". Это означает, что любое содержимое, добавленное в эти разделы, будет считаться основным содержимым сайта и будет отображаться на видном месте. Это может быть полезно для организации и определения приоритетов контента на сайте.
  mainSections = ["post","posts"]
  #`logo = "../../../../static/img/icon.png"` задает путь к файлу изображения логотипа сайта. Файл логотипа находится в директории `static` сайта, а путь является относительным к текущему местоположению в конфигурационном файле. В данном случае файл логотипа находится в каталоге `img` в каталоге `static`, а путь включает три уровня родительских каталогов (`../../..`) для достижения корневого каталога сайта.
  logo = "../../../../static/img/icon.png"
  #`favicon = "../../../../static/img/favicon.ico"` задает путь к файлу favicon сайта. Фавикон - это маленький значок, который появляется на вкладке браузера и в строке закладок, чтобы помочь пользователям легко идентифицировать сайт. Фавикон находится в директории `static` сайта, а путь к нему задается относительно текущего местоположения в конфигурационном файле. В данном случае файл favicon находится в каталоге `img` в каталоге `static`, а путь включает три уровня родительских каталогов (`../../..`) для достижения корневого каталога сайта.
  favicon = "../../../../static/img/favicon.ico"
  #`dateFormat = "2 Января, 2006"` - это установка формата даты для сайта "2 Января, 2006", который является русскоязычным форматом отображения дат. Этот формат будет использоваться для отображения дат на всем сайте, например, в сообщениях блога или на главной странице. Формат включает в себя день месяца, название месяца на русском языке и год.
  dateFormat = "2 Января, 2006"
  #`commit = false` - это параметр в разделе `[Params]` конфигурационного файла сайта Hugo, который отключает автоматическое создание Git-коммитов при создании сайта. По умолчанию Hugo будет создавать Git-коммит для каждой сборки сайта, что может быть полезно для отслеживания изменений и поддержания контроля версий. Однако установка `commit = false` не позволит Hugo создавать эти коммиты, что может быть желательно в некоторых ситуациях, например, при тестировании или при отладке сайта.
  commit = false
  #`rss = true` - это параметр в разделе `[Params]` конфигурационного файла сайта Hugo, который позволяет генерировать RSS-ленту для сайта. RSS (Really Simple Syndication) - это формат для доставки подписчикам регулярно обновляемого контента, такого как сообщения в блогах или новостные статьи. Установив `rss = true`, Hugo автоматически создаст RSS-канал для сайта, доступ к которому можно получить, добавив `/index.xml` к URL сайта. Это позволит посетителям легко подписаться на содержание сайта и получать обновления в своем RSS-ридере.
  rss = true
  #`comments = true` — это параметр в файле конфигурации сайта Hugo, который включает комментарии на сайте. Это означает, что посетители веб-сайта могут оставлять комментарии к сообщениям или страницам, что может помочь повысить вовлеченность и создать чувство общности на сайте.
  #comments = true
  #`readingTime = true` — это параметр в файле конфигурации для веб-сайта Hugo, который позволяет отображать предполагаемое время чтения для каждого сообщения на веб-сайте. Эта функция вычисляет приблизительное время, которое потребуется среднестатистическому читателю, чтобы прочитать сообщение, и отображает его рядом с заголовком сообщения или в метаданных сообщения.
  readingTime = true
  #`wordCount = true` — это параметр в файле конфигурации веб-сайта Hugo, который включает отображение количества слов для каждого сообщения на веб-сайте. Эта функция вычисляет приблизительное количество слов в каждом сообщении и отображает его рядом с заголовком сообщения или в метаданных сообщения.
  wordCount = true
  #`useHLJS = true` — это параметр в файле конфигурации веб-сайта Hugo, который позволяет использовать библиотеку Highlight.js для подсветки синтаксиса фрагментов кода на веб-сайте. Если для этого параметра установлено значение true, Hugo автоматически загрузит библиотеку Highlight.js и применит подсветку синтаксиса ко всем фрагментам кода на веб-сайте.
  useHLJS = true
  #`socialShare = true` — это параметр в файле конфигурации веб-сайта Hugo, который включает функцию обмена в социальных сетях на веб-сайте. Это означает, что посетители веб-сайта могут легко делиться контентом с веб-сайта в своих учетных записях в социальных сетях, таких как Facebook, Twitter или LinkedIn, нажимая кнопки обмена в социальных сетях, отображаемые на веб-сайте. Включение этого параметра может помочь повысить видимость и охват контента веб-сайта в социальных сетях.
  #socialShare = true
  #`delayDisqus = true` — это параметр в файле конфигурации веб-сайта Hugo, который откладывает загрузку системы комментариев Disqus до тех пор, пока пользователь не прокрутит вниз до раздела комментариев. Это может помочь повысить скорость загрузки веб-сайта и уменьшить количество ненужных запросов к серверу Disqus.
  #delayDisqus = true
  #`showRelatedPosts = true` — это параметр в файле конфигурации веб-сайта Hugo, который включает отображение связанных сообщений на веб-сайте. Эта функция анализирует содержание каждого сообщения и предлагает другие сообщения, которые могут быть интересны читателю, на основе похожих тем или тегов. Включение этого параметра может помочь повысить вовлеченность и удержать читателей на сайте в течение более длительного периода времени.
  showRelatedPosts = true
  #`sine = 2022` устанавливает начальный год для сайта. Это означает, что любая дата, отображаемая на сайте, будет относиться к 2022 году. Например, если сообщение было опубликовано в 2023 году, оно будет отображаться как «1 год назад», а не как «в будущем».
  since = 2022
  #`hideAuthor = true` — это параметр в файле конфигурации веб-сайта Hugo, который скрывает информацию об авторе для каждого сообщения на веб-сайте. Это означает, что имя автора или любая другая информация об авторе не будут отображаться рядом с сообщением.
  #hideAuthor = true
  #`gcse = "012345678901234567890:abcdefghijk"` устанавливает идентификатор системы пользовательского поиска Google (GCSE) для веб-сайта. Это позволяет веб-сайту использовать функцию поиска Google для предоставления результатов поиска для сайта. Идентификатор — это уникальный идентификатор конкретного GCSE, который был настроен для веб-сайта.
  #gcse = "012345678901234567890:abcdefghijk"

[Author]
  # Это секция конфигурации для настройки информации об авторе и ссылок на социальные сети для проекта. Секция включает поля для различных платформ социальных сетей, таких как Facebook, GitHub, Twitter и YouTube, а также другую информацию, такую как электронная почта и веб-сайт. Значения для каждого поля должны быть заменены собственными именами пользователей или URL-адресами автора.
  name = "EXAMPLE"
  #website = "yourwebsite.com"
  #email = "youremail@domain.com"
  #facebook = "username"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  youtube = "channel/EXAMPLE"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  vk = "EXAMPLE"
  #paypal = "username"
  telegram = "EXAMPLE"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  discord = "invite/2HKWvyYbMj"
  #strava = "userid"
  steam = "groups/EXAMPLE"

#Это секция конфигурации для главного меню веб-сайта. Она определяет пункты меню, их имена, URL-адреса и веса (которые определяют их порядок в меню).
# [[menu.main]]
#     name = "Подключиться"
#     url = "http://connect.EXAMPLE.COM/"
#     weight = 1

[[menu.main]]
    name = "Почта"
    url = "https://mail.EXAMPLE.COM/"
    weight = 1

[[menu.main]]
    identifier = "section_helpful"
    name = "Полезное"
    weight = 2

[[menu.main]]
    parent = "section_helpful"
    name = "Правила"
    url = "page/rules/"
    weight = 1

[[menu.main]]
    parent = "section_helpful"
    name = "Информация"
    url = "page/info/"
    weight = 2

# [[menu.main]]
#     parent = "section_helpful"
#     name = "Блог"
#     url = "page/blog/"
#     weight = 3!

[[menu.main]]
    parent = "section_helpful"
    name = "Мониторинг"
    url = "https://monitoring.EXAMPLE.COM/"
    weight = 3

[[menu.main]]
    identifier = "section_contact"
    name = "Связаться с нами"
    weight = 3

[[menu.main]]
    parent = "section_contact"
    name = "Группа Steam"
    url = "https://steamcommunity.com/groups/EXAMPLE/"
    weight = 1

[[menu.main]]
    parent = "section_contact"
    name = "Канал Telegram"
    url = "https://EXAMPLE.t.me/"
    weight = 2

[[menu.main]]
    parent = "section_contact"
    name = "Cообщество VK"
    url = "https://vk.com/EXAMPLE/"
    weight = 3

[[menu.main]]
    parent = "section_contact"
    name = "Сервер Matrix"
    url = "https://chat.EXAMPLE.COM/"
    weight = 4

[[menu.main]]
    parent = "section_contact"
    name = "Сервер Discord"
    url = "https://discord.com/invite/EXAMPLE/"
    weight = 5

# [[menu.main]]
#     name = "About"
#     url = "page/about/"
#     weight = 3

# [[menu.main]]
#     name = "Tags"
#     url = "tags"
#     weight = 3